### ISSUE TITLE
Failed to save payment method: An error has occurred.

### ISSUE THREAD

**Issue by garpunkal** [vendrhub/vendr-payment-provider-stripe#1]
I changed the **Default Pricing** for the payment method on my stripe payment provider from £0.00 to £9.99. I then tried to change it back to £0.00 and the following error occured: 

`Exception
System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.vendrPaymentMethodCountryRegionPrice' with unique index 'IX_vendrPaymentMethodCountryRegionPrice_compositeId'. The duplicate key value is (cbdd1654-86ed-4f8a-bee8-bf669c81a6bb, <NULL>, <NULL>, f9359959-f39b-42b4-9bb9-0d7a307c362e).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.InsertBatch[T](IEnumerable`1 pocos, BatchOptions options)
ClientConnectionId:efda61dd-9fcb-4b6e-862e-e2379b540db1
Error Number:2601,State:1,Class:14`

If you need anymore information, just let me know.

**Comment by mattbrailsford** [comment]
Hey @garpunkal this actually looks like a core persistence issue, rather than an issue with the Stripe payment provider itself. Can you log it over on https://github.com/vendrhub/vendr/issues ?

Many thanks

**Comment by mattbrailsford** [comment]
In fact, I've fixed this now so no need to re-report 👍
